default: &default
  adapter: mysql2
  encoding: utf8
  pool:     5
  username: root
  host:     localhost

development:
  <<: *default
  database: afsite_dev


test:
  <<: *default
  database: afsite_test

production:
  <<: *default
  password: abcD123
  database: afsite_prod
