default: &default
  adapter: mysql2
  encoding: utf8
  pool:     5
  username: root
  password:
  host:     localhost

development:
  <<: *default
  database: afsite_dev


test:
  <<: *default
  database: afsite_test

prod:
  <<: *default
  database: afsite_prod
